name: Release

on:
  push:
    tags:
      - v*

jobs:
  tests:
    uses: vbrandl/petnames-generator/.github/workflows/ci.yml@master

  release:
    name: Release
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
